@set allusersprofile=c:\programdata
@set appdata=c:\users\sovahiblack\appdata\roaming
@set ascon_polynom_library=1
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=vineta
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files\microsoft visual studio\2022\professional\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set efc_7092=1
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set external_include=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\include;c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\atlmfc\include;c:\program files\microsoft visual studio\2022\professional\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.26100.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\cppwinrt
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set gcexpconfigusedinsession=3
@set homedrive=c:
@set homepath=\users\sovahiblack
@set htmlhelpdir=c:\program files (x86)\html help workshop
@set include=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\include;c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\atlmfc\include;c:\program files\microsoft visual studio\2022\professional\vc\auxiliary\vs\include;c:\program files (x86)\windows kits\10\include\10.0.26100.0\ucrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\um;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\shared;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\winrt;c:\program files (x86)\windows kits\10\\include\10.0.26100.0\\cppwinrt
@set kompas_sdk=c:\program files\ascon\kompas-3d v22\sdk\
@set lib=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\atlmfc\lib\x86;c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\lib\x86;c:\program files (x86)\windows kits\10\lib\10.0.26100.0\ucrt\x86;c:\program files (x86)\windows kits\10\\lib\10.0.26100.0\\um\x86
@set libpath=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\atlmfc\lib\x86;c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\lib\x86;c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.26100.0;c:\program files (x86)\windows kits\10\references\10.0.26100.0;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\sovahiblack\appdata\local
@set logonserver=\\vineta
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set number_of_processors=12
@set os=windows_nt
@set path=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\bin\hostx86\x86;c:\program files\microsoft visual studio\2022\professional\common7\ide\vc\vcpackages;c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\testwindow;c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files\microsoft visual studio\2022\professional\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\;c:\program files (x86)\html help workshop;c:\program files\microsoft visual studio\2022\professional\team tools\diagnosticshub\collector;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\\x86;c:\program files (x86)\windows kits\10\bin\\x86;c:\program files\microsoft visual studio\2022\professional\\msbuild\current\bin\amd64;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files\microsoft visual studio\2022\professional\common7\ide\;c:\program files\microsoft visual studio\2022\professional\common7\tools\;c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\bin\hostx86\x86;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x86;c:\program files\microsoft visual studio\2022\professional\common7\tools;c:\program files\microsoft visual studio\2022\professional\common7\ide;c:\program files (x86)\html help workshop;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\perl64\site\bin;c:\perl64\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\program files\winmerge;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\users\sovahiblack\appdata\local\microsoft\windowsapps;c:\users\sovahiblack\appdata\local\githubdesktop\bin;c:\users\sovahiblack\.dotnet\tools;c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files\microsoft visual studio\2022\professional\common7\ide\vc\linux\bin\connectionmanagerexe
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pgdata=c:\program files\ascon\kompas-3d v22\libs\polynomlib\templates\localbase\data
@set pkgdefapplicationconfigfile=c:\users\sovahiblack\appdata\local\microsoft\visualstudio\17.0_4e4d3b60\devenv.exe.config
@set platform=x86
@set polynom_install_path=c:\program files\ascon\kompas-3d v22\libs\polynomlib\
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 154 stepping 4, genuineintel
@set processor_level=6
@set processor_revision=9a04
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files\microsoft visual studio\2022\professional\msbuild
@set pvsbuildtools_extensionspath_vs2022=c:\program files\microsoft visual studio\2022\professional\msbuild
@set pvsbuildtools_installdir_current=c:\program files\microsoft visual studio\2022\professional
@set pvsbuildtools_installdir_vs2022=c:\program files\microsoft visual studio\2022\professional
@set pvsbuildtools_netcoresdkmajorversion=9
@set pvsbuildtools_vctargetspath_current=c:\program files\microsoft visual studio\2022\professional\msbuild\microsoft\vc\v170\
@set pvsbuildtools_visualstudioversion_current=17.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\9.0.100\sdks
@set servicehubhostservicebrokerpipename=\\.\pipe\855a585d-8ae7-4226-83c1-f8f731d415f3
@set servicehublogsessionkey=618921d0
@set sessionname=console
@set signinwithhometenantonly=false
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\sovahiblack\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\sovahiblack\appdata\local\temp
@set ucrtversion=10.0.26100.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=vineta
@set userdomain_roamingprofile=vineta
@set username=sovahiblack
@set userprofile=c:\users\sovahiblack
@set vcideinstalldir=c:\program files\microsoft visual studio\2022\professional\common7\ide\vc\
@set vcinstalldir=c:\program files\microsoft visual studio\2022\professional\vc\
@set vctoolsinstalldir=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\
@set vctoolsredistdir=c:\program files\microsoft visual studio\2022\professional\vc\redist\msvc\14.44.35112\
@set vctoolsversion=14.44.35207
@set visualstudiodir=d:\sovahiblack\documents\visual studio 2022
@set visualstudioedition=microsoft visualÿstudio professionalÿ2022
@set visualstudioversion=17.0
@set vs110comntools=c:\program files (x86)\microsoft visual studio 11.0\common7\tools\
@set vs120comntools=c:\program files (x86)\microsoft visual studio 12.0\common7\tools\
@set vs170comntools=c:\program files\microsoft visual studio\2022\professional\common7\tools\
@set vsappiddir=c:\program files\microsoft visual studio\2022\professional\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=17.14.23
@set vsinstalldir=c:\program files\microsoft visual studio\2022\professional\
@set vslang=1049
@set vspermonitordpiawarenessenabled.7388=true
@set vsskuedition=professional
@set vs_perf_session_gcheapcount=2
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.26100.0;c:\program files (x86)\windows kits\10\references\10.0.26100.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.26100.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.26100.0\
@set windowssdkversion=10.0.26100.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v8.1a\bin\netfx 4.5.1 tools\
@set zes_enable_sysman=1
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files\microsoft visual studio\2022\professional\vc\tools\msvc\14.44.35207\bin\hostx86\x86;c:\program files (x86)\windows kits\10\bin\10.0.26100.0\x86;c:\program files\microsoft visual studio\2022\professional\common7\tools;c:\program files\microsoft visual studio\2022\professional\common7\ide;c:\program files (x86)\html help workshop;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\perl64\site\bin;c:\perl64\bin;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\dotnet\;c:\program files\winmerge;c:\program files\microsoft sql server\110\tools\binn\;c:\program files (x86)\microsoft sdks\typescript\1.0\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\users\sovahiblack\appdata\local\microsoft\windowsapps;c:\users\sovahiblack\appdata\local\githubdesktop\bin;c:\users\sovahiblack\.dotnet\tools

@call "cl.exe" @"D:\SovaHiBlack-Engine\Sources\xrEngine\xrGame\visual_memory_params.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1